import type { inferRouterOutputs } from "@trpc/server";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

import { api } from "../utils/api";
import type { CardRouter } from '../server/api/routers/card';

type LangKey = 'en_US' | 'ja_JP' | 'de_DE' | 'fr_FR' | 'es_ES' | 'it_IT' | 'pt_PT' | 'ru_RU' | 'ko_KR' | 'zh_TW' | 'zh_CN';
type Cards = inferRouterOutputs<CardRouter>['filter'];
type Card = Cards[0] & {
  image: Record<LangKey, string>
  name: Record<LangKey, string>
};

const Card = ({ card }: { card: Card }) => {
  return (
    <li>
      <Image
        src={card.image.en_US}
        alt={card.slug}
        width={200}
        height={276.56}
      />
      <span>{card.name.en_US}</span>
      <span>{card.tier}</span>
    </li>
  );
}

const Home: NextPage = () => {
  const [name, setName] = useState('');
  const cardQuery = api.card.filter.useQuery<unknown, Card[]>({ name });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <input value={name} onChange={(e) => setName(e.target.value)} />
        <ul className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
          {cardQuery.data?.map((card) => (<Card key={card.id} card={card} />))}
        </ul>
      </main>
    </>
  );
};

export default Home;
