-- CreateTable
CREATE TABLE "Card" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "collectible" BOOLEAN NOT NULL,
    "slug" TEXT NOT NULL,
    "classId" INTEGER NOT NULL,
    "multiClassIds" INTEGER[],
    "minionTypeId" INTEGER,
    "cardTypeId" INTEGER NOT NULL,
    "cardSetId" INTEGER NOT NULL,
    "rarityId" INTEGER,
    "artistName" TEXT,
    "health" INTEGER NOT NULL,
    "attack" INTEGER NOT NULL,
    "manaCost" INTEGER NOT NULL,
    "name" JSONB NOT NULL,
    "text" JSONB NOT NULL,
    "image" JSONB NOT NULL,
    "imageGold" JSONB NOT NULL,
    "flavorText" JSONB NOT NULL,
    "cropImage" TEXT NOT NULL,
    "parentId" INTEGER NOT NULL,
    "childIds" INTEGER[],
    "tier" INTEGER,
    "hero" BOOLEAN NOT NULL DEFAULT false,
    "quest" BOOLEAN NOT NULL DEFAULT false,
    "reward" BOOLEAN NOT NULL DEFAULT false,
    "upgradeId" INTEGER,
    "companionId" INTEGER,

    CONSTRAINT "Card_pkey" PRIMARY KEY ("id")
);
