
export const keywords = [
  { id: 0, slug: "", name: "" },
  {
    id: 198,
    slug: "avenge",
    name: "Avenge (X)",
    refText: "Does something after X friendly minions die.",
    text: "Does something after X friendly minions die.",
    gameModes: [2],
  },
  {
    id: 8,
    slug: "battlecry",
    name: "Battlecry",
    refText: "Does something when you play it from your hand.",
    text: "Does something when you play it from your hand.",
    gameModes: [1, 2, 4, 5, 6, 7],
  },
  {
    id: 109,
    slug: "blood-gem",
    name: "Blood Gem",
    refText: "A spell that gives a friendly minion +1/+1.",
    text: "A spell that gives a friendly minion +1/+1.",
    gameModes: [2],
  },
  {
    id: 12,
    slug: "deathrattle",
    name: "Deathrattle",
    refText: "Does something when it dies.",
    text: "Does something when it dies.",
    gameModes: [1, 2, 4, 5, 6, 7],
  },
  {
    id: 21,
    slug: "discover",
    name: "Discover",
    refText: "Choose one of three cards to add to your hand.",
    text: "Choose one of three cards to add to your hand.",
    gameModes: [1, 2, 4, 5],
  },
  {
    id: 3,
    slug: "divine-shield",
    name: "Divine Shield",
    refText: "The first time a Shielded minion takes damage, ignore it.",
    text: "The first time this minion takes damage, ignore it.",
    gameModes: [1, 2, 4, 5, 6],
  },
  {
    id: 99,
    slug: "frenzy",
    name: "Frenzy",
    refText: "A one-time effect after this survives damage.",
    text: "A one-time effect after this survives damage.",
    gameModes: [1, 2, 4, 5],
  },
  {
    id: 17,
    slug: "immune",
    name: "Immune",
    refText: "Can't be targeted by enemies or damaged.",
    text: "Can't be targeted by enemies or damaged.",
    gameModes: [1, 2, 4, 5, 6],
  },
  {
    id: 66,
    slug: "modular",
    name: "Magnetic",
    refText: "Play this to the left of a Mech to fuse them together!",
    text: "Play this to the left of a Mech to fuse them together!",
    gameModes: [1, 2],
  },
  {
    id: 32,
    slug: "poisonous",
    name: "Poisonous",
    refText: "Destroy any minion damaged by this.",
    text: "Destroy any minion damaged by this.",
    gameModes: [1, 2, 4, 5],
  },
  {
    id: 31,
    slug: "quest",
    name: "Quest",
    refText: "Starts in your hand. Complete for a reward.",
    text: "Starts in your hand. Complete for a reward.",
    gameModes: [1, 2, 4, 5],
  },
  {
    id: 78,
    slug: "reborn",
    name: "Reborn",
    refText: "Resurrects with 1 Health the first time it dies.",
    text: "Resurrects with 1 Health the first time it dies.",
    gameModes: [1, 2, 4, 5],
  },
  {
    id: 196,
    slug: "refresh",
    name: "Refresh",
    refText: "Replace Bob's Tavern with new minions.",
    text: "Replace Bob's Tavern with new minions.",
    gameModes: [2],
  },
  {
    id: 234,
    slug: "spellcraft",
    name: "Spellcraft",
    refText: "Get a temporary spell every turn.",
    text: "Get a temporary spell every turn.",
    gameModes: [2],
  },
  {
    id: 92,
    slug: "start-of-combat",
    name: "Start of Combat",
    refText: "Does something at the start of the Combat Phase.",
    text: "Does something at the start of the Combat Phase.",
    gameModes: [2],
  },
  {
    id: 252,
    slug: "bacon_stealth",
    name: "Stealth",
    refText: "Can't be attacked until it attacks.",
    text: "Can't be attacked until it attacks.",
    gameModes: [2],
  },
  {
    id: 1,
    slug: "taunt",
    name: "Taunt",
    refText: "Enemies must attack minions that have Taunt.",
    text: "Enemies must attack this minion.",
    gameModes: [1, 2, 4, 5, 6, 7],
  },
  {
    id: 11,
    slug: "windfury",
    name: "Windfury",
    refText: "Can attack twice each turn.",
    text: "Can attack twice each turn.",
    gameModes: [1, 2, 4, 5, 6],
  },
] as const;

export const getKeywordsByIds = (ids: number[]) =>
  keywords.filter((keyword) => ids.includes(keyword.id));


export const CardTiers = [
  { title: "tier 1", filter: { tier: 1 } },
  { title: "tier 2", filter: { tier: 2 } },
  { title: "tier 3", filter: { tier: 3 } },
  { title: "tier 4", filter: { tier: 4 } },
  { title: "tier 5", filter: { tier: 5 } },
  { title: "tier 6", filter: { tier: 6 } },
] as const;

export const MinionTypes = {
  NoType: 0,
  Beast: 20,
  Demon: 15,
  Dragon: 24,
  Elemental: 18,
  Mech: 17,
  Murloc: 14,
  Naga: 92,
  Pirate: 23,
  Quillboar: 43,
  Undead: 11,
} as const;